name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.20']
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Go build (source)
        run: make

      - name: Go build (tests)
        run: make test
